

* LEARNING

* English Vocab
  juggle - धोखा देना, जादू करना, हाथ की सफाई करना ,एक साथ संभालना, हथकंडा करना

* TODO English Grammar practise 
  DEADLINE: <2021-09-16 Thu>

* TODO Maths -Practise two variable equestions solving using substitution method
  DEADLINE: <2021-09-20 Mon>
   (a) x + y = 15                    x - y = 3

  (b) x + y = 0                      x - y = 2

  (c) 2x - y = 3                   4x + y = 3

  (d) 2x - 9y = 9               5x + 2y = 27

  (e) x + 4y = -4               3y - 5x = -1

  (f) 2x - 3y = 2                  x + 2y = 8

  (g) x + y = 7                  2x - 3y = 9

  (h) 11y + 15x = -23        7y - 2x = 20

   (i) 5x - 6y = 2                6x - 5y = 9

* English Grammar
  - [[https://www.perfect-english-grammar.com/grammar-exercises.html][Practice english]]
  - [[https://www.perfect-english-grammar.com/past-perfect-continuous-use.html][Past Perfect Continous]]
    We use the past perfect continuous to refer to an ONGOING ACTION
    that ended before ANOTHER  ACTION/EVENT in the past. 
    For example,
    I had been  looking for a job for several months when I found this position.
    As with all continuous forms, when we use the past perfect continuous we’re focusing on the action itself and possibly also the effect on the subject, rather than its completion. For example,
    The workers had been unloading the truck when the storm started.
    We don’t know if the unloading was completed or not, and it’s not important. The focus is just on their action. 
    Here's how to make the past perfect continuous. It's 'had' + been (the past participle of 'be')+ verb-ing
    Firstly, let's look at the positive form:
    - I had been living
    - You had been going
    - She had been sleeping
    - He had been working
    - It had been raining
    - We had been studying
    - They had been cooking

    Next, the negative form:
    - I had not been trying (I hadn't been..)
    - You had not been working (you hadn't been..)
    - She had not been crying (she hadn't been..)
    - He had not been shopping (he hadn't been..)
    - It had not been snowing (it hadn't been..)
    - We had not been reading (we hadn't been..)
    - They had not been running (they hadn't been..)
    - Here's an exercise about the negative

    It's pretty easy to make the question too.

    'Yes / no' questions:
    - Had I been working?
    - Had you been sleeping?
    - Had she been reading?
    - Had he been watching TV?
    - Had it been raining?
    - Had we been drinking?
    - Had they been eating?

    'Wh' questions:
      - Where had I been working? 
      - How long had you been sleeping?
      - What had she been reading?
      - How long had he been watching TV?
      - How long had it been raining?
      - What had we been drinking?
      - Why had they been eating?

    - When should I use the Past Perfect Continuous?
      1. Something that started in the past and continued up to another
        action or time in the past. The past perfect continuous tells us 'how long',just like the present perfect continuous, but this time the action continues up to a point in the past rather than the present. Usually we use 'for + time'
        Examples: 
         1. She had been working at that company for a year when she met James.
         2. I'd been walking for hours when I finally found the house.
         3. We'd been living in Berlin for three months when we had to
            leave.

      2. Something that finished just before another event in the
         past. This is usually used to show a result at a time in the
        past. It's very similar to the present perfect continuous, but the
         action finishes before another time in the past, rather than
         finishing before the present.

         Examples

         1. The pavement was wet, it had been raining. (The rain had finished before the time I'm describing in the past. We could see the result of the rain.)
         2. The children had been playing and so the room was a mess!
         3. I'd been working before I saw you and that's why I was
            really tired.

      3. [[https://www.perfect-english-grammar.com/past-perfect-continuous-exercise-3.html][Practise Past Continous]]
  - [[https://www.wallstreetenglish.com/exercises/using-the-past-perfect-tense-in-english][Past Perfect]]

    How to form the past perfect
    We form the past perfect by using ‘had’ and the past participle of
    the verb.
    For example,

    “You had met him before.”

    To make questions we invert the auxiliary verb had and the subject:

       “Had you met him before?”

    And to make negative forms we add ‘not’ to ‘had’:
       “You hadn’t met him before.”

      We use the past perfect to refer to something that happened MOIRE IN
      THE PAST than something else. For this reason it’s almost always used with another phrase in the simple past. For example,

       Bob was exhausted. He had worked hard all day.It’s common to use the
       following adverbs with the past perfect like already, just, never,
       previously. 
     These are positioned between had and the past participle. We can also use yet with the past perfect, and put it at the end of the sentence. Here are some examples.

     When Miguel arrived, the party had already started.

     The kids were really excited about visiting the fun park. They’d never been before.

     I didn’t go to see the film with my friends because I’d already seen it.

     When we went outside it had just begun to rain.

    The new CEO joined the company last month. She’d previously worked for a pharmaceutical firm.

    My brother sold his car on Saturday. He’d had it for 20 years!

    When we got to the airport we realized we’d left the tickets at home.

    Tim had just retired when you joined the firm, hadn’t he?

   Had the boys already done their homework when you spoke to them?
  - [[https://www.perfect-english-grammar.com/present-simple-use.html][PresntTense Forms]]
  - Modal Verb
    Modal verbs add meaning to the main verb in a sentence by
    expressing possibility, ability, permission, or obligation.
    words : can	could	may	might	will  would	must	shall	should	ought to

 
   
  


